### ISSUE TITLE
Dcat, circular reference ?

### ISSUE THREAD

**Issue by barthanssens** [openplannerteam/opentransportdatabe#6]
The dcat file has these  statements

```
... dcterms:publisher <https://openplanner.team/>
...
<https://openplanner.team/> foaf:page <https://openplanner.team/>
```

Not sure if that is the intention, but it could create some issues (eg in SPARQL queries) and creates ambiguity (e.g. if I'd like to add statements on the webpage, but not on the publishing organization), not to mention reasoning :-)

**Comment by julianrojas87** [comment]
Changed Open Planner URI on [this commit](https://github.com/openplannerteam/opentransportdatabe/commit/c1fbc0ccbaa98ab5187cfffdd3f1a1d52bcc8c72)
