### ISSUE TITLE
Dcat, range of rights

### ISSUE THREAD

**Issue by barthanssens** [openplannerteam/opentransportdatabe#7]
IIRC the range of both dcterms:rights and dcterms:accessRights is a class, thus an IRI should be used (e.g. from https://publications.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/access-right)  and not a literal like "public"

**Comment by julianrojas87** [comment]
Fixed on [this commit](https://github.com/openplannerteam/opentransportdatabe/commit/2977a81b41f32f52eedea4e3ee514cba4a232d7a).
